const matchingScreen =
    document.getElementById("matching-screen");

const conversation =
    document.getElementById("conversation");

const chatStatus =
    document.getElementById("chat-status");

const chatDescription =
    document.getElementById("chat-description");

const chatActionBtn =
    document.getElementById("chat-action-btn");

const messageForm =
    document.getElementById("message-form");

const messageInput =
    document.getElementById("message-input");

const messages =
    document.getElementById("messages");

const skipButton =
    document.getElementById("skip-btn");

const leaveChatButton =
    document.getElementById("leave-chat");


let randomSocket = null;
let randomConnected = false;

/*
 * IMPORTANT:
 * This is the ID generated by the RANDOM CHAT SERVER.
 * It is different from the localStorage ID used by groups.
 */
let randomServerUserId = null;


/* =========================
   RANDOM CHAT UI
========================= */

function showRandomWaiting(
    text = "Looking for someone to chat with..."
) {
    randomConnected = false;

    if (matchingScreen) {
        matchingScreen.style.display = "flex";
    }

    if (conversation) {
        conversation.style.display = "none";
    }

    if (chatStatus) {
        chatStatus.textContent = "Searching...";
    }

    if (chatDescription) {
        chatDescription.textContent = text;
    }

    if (messages) {
        messages.innerHTML = "";
    }
}


function showRandomConversation() {
    randomConnected = true;

    if (matchingScreen) {
        matchingScreen.style.display = "none";
    }

    if (conversation) {
        conversation.style.display = "flex";
    }

    if (chatStatus) {
        chatStatus.textContent = "Connected";
    }

    if (chatDescription) {
        chatDescription.textContent =
            "You are chatting anonymously.";
    }

    if (messageInput) {
        messageInput.focus();
    }
}


/* =========================
   RANDOM CHAT CONNECTION
========================= */

function connectRandomChat() {
    if (!matchingScreen || !conversation) {
        return;
    }

    randomServerUserId = null;

    showRandomWaiting();

    const protocol =
        window.location.protocol === "https:"
            ? "wss:"
            : "ws:";

    randomSocket =
        new WebSocket(
            `${WS_URL}/ws/random`
        );


    randomSocket.addEventListener(
        "open",
        function () {
            console.log(
                "Random chat connected"
            );
        }
    );


    randomSocket.addEventListener(
        "message",
        function (event) {

            let data;

            try {
                data = JSON.parse(event.data);
            } catch (error) {
                console.error(
                    "Invalid random chat data:",
                    error
                );
                return;
            }

            console.log(
                "RANDOM EVENT:",
                data
            );


            /* =====================
               WAITING
            ===================== */

            if (data.type === "waiting") {

                /*
                 * Backend sends our server-side
                 * anonymous ID here.
                 */
                if (data.user_id) {
                    randomServerUserId =
                        data.user_id;

                    console.log(
                        "My random server ID:",
                        randomServerUserId
                    );
                }

                showRandomWaiting(
                    data.message ||
                    "Looking for someone to chat with..."
                );
            }


            /* =====================
               MATCHED
            ===================== */

            else if (data.type === "matched") {

                /*
                 * Store our server-side ID again
                 * when a match is created.
                 */
                if (data.user_id) {
                    randomServerUserId =
                        data.user_id;

                    console.log(
                        "Matched - my server ID:",
                        randomServerUserId
                    );
                }

                showRandomConversation();
            }


            /* =====================
               MESSAGE
            ===================== */

            else if (data.type === "message") {

                if (!messages) {
                    return;
                }

                /*
                 * THIS FIXES THE BUBBLE PROBLEM.
                 *
                 * If sender_id equals our server ID,
                 * show the message on the RIGHT.
                 *
                 * Otherwise show it on the LEFT.
                 */
                const isMine =
                    data.sender_id ===
                    randomServerUserId;

                addRandomMessage(
                    data.content,
                    isMine
                );
            }


            /* =====================
               PARTNER SKIPPED
            ===================== */

            else if (
                data.type === "partner_skipped"
            ) {

                showRandomWaiting(
                    "The other person skipped. Finding someone new..."
                );
            }


            /* =====================
               PARTNER LEFT
            ===================== */

            else if (
                data.type === "partner_left"
            ) {

                randomConnected = false;

                if (chatStatus) {
                    chatStatus.textContent =
                        "Partner left";
                }

                if (chatDescription) {
                    chatDescription.textContent =
                        "The other person left the chat.";
                }

                if (matchingScreen) {
                    matchingScreen.style.display =
                        "flex";
                }

                if (conversation) {
                    conversation.style.display =
                        "none";
                }

                if (messages) {
                    messages.innerHTML = "";
                }
            }


            /* =====================
               SKIP BLOCKED
            ===================== */

            else if (
                data.type === "skip_blocked"
            ) {

                alert(
                    data.message ||
                    "You cannot skip right now."
                );
            }


            /* =====================
               ERROR
            ===================== */

            else if (
                data.type === "error"
            ) {

                console.error(
                    "Random chat error:",
                    data.message
                );
            }
        }
    );


    randomSocket.addEventListener(
        "close",
        function () {

            randomConnected = false;

            if (chatStatus) {
                chatStatus.textContent =
                    "Disconnected";
            }

            if (chatDescription) {
                chatDescription.textContent =
                    "Connection closed.";
            }
        }
    );


    randomSocket.addEventListener(
        "error",
        function (error) {

            console.error(
                "Random chat error:",
                error
            );
        }
    );
}


/* =========================
   RANDOM MESSAGE UI
========================= */

function addRandomMessage(
    content,
    isMine
) {
    if (!messages) {
        return;
    }

    const message =
        document.createElement("div");

    /*
     * Your message:
     * message sent
     *
     * Partner message:
     * message received
     */
    message.className =
        isMine
            ? "message sent"
            : "message received";


    const paragraph =
        document.createElement("p");

    paragraph.textContent =
        content;

    message.appendChild(
        paragraph
    );

    messages.appendChild(
        message
    );

    messages.scrollTop =
        messages.scrollHeight;
}


/* =========================
   RANDOM SEND MESSAGE
========================= */

if (messageForm) {

    messageForm.addEventListener(
        "submit",
        function (event) {

            event.preventDefault();

            if (
                !randomSocket ||
                randomSocket.readyState !==
                    WebSocket.OPEN
            ) {
                return;
            }

            if (!randomConnected) {
                return;
            }

            const content =
                messageInput
                    ? messageInput.value.trim()
                    : "";

            if (!content) {
                return;
            }

            randomSocket.send(
                JSON.stringify({
                    type: "message",
                    content: content
                })
            );

            messageInput.value = "";

            messageInput.focus();
        }
    );
}


/* =========================
   RANDOM SKIP
========================= */

if (skipButton) {

    skipButton.addEventListener(
        "click",
        function () {

            if (
                !randomSocket ||
                randomSocket.readyState !==
                    WebSocket.OPEN
            ) {
                return;
            }

            if (!randomConnected) {
                return;
            }

            randomSocket.send(
                JSON.stringify({
                    type: "skip"
                })
            );
        }
    );
}


/* =========================
   RANDOM LEAVE
========================= */

if (leaveChatButton) {

    leaveChatButton.addEventListener(
        "click",
        function () {

            if (
                randomSocket &&
                randomSocket.readyState ===
                    WebSocket.OPEN
            ) {

                randomSocket.send(
                    JSON.stringify({
                        type: "leave"
                    })
                );

                randomSocket.close();
            }

            window.location.href =
                "index.html";
        }
    );
}


/* =========================
   OLD ACTION BUTTON
========================= */

if (chatActionBtn) {

    chatActionBtn.addEventListener(
        "click",
        function () {

            if (
                randomSocket &&
                randomSocket.readyState ===
                    WebSocket.OPEN
            ) {

                if (randomConnected) {

                    randomSocket.send(
                        JSON.stringify({
                            type: "skip"
                        })
                    );

                } else {

                    randomSocket.close();

                    window.location.href =
                        "index.html";
                }

            } else {

                window.location.href =
                    "index.html";
            }
        }
    );
}



/* =========================
   START RANDOM CHAT
========================= */

if (
    matchingScreen &&
    conversation
) {
    connectRandomChat();
}
