/* =========================
   BACKEND
========================= */

const API_URL =
    window.location.hostname === "127.0.0.1" ||
    window.location.hostname === "localhost"
        ? "http://127.0.0.1:8000"
        : "https://randomconnect-api.onrender.com";

const WS_URL =
    window.location.hostname === "127.0.0.1" ||
    window.location.hostname === "localhost"
        ? "ws://127.0.0.1:8000"
        : "wss://randomconnect-api.onrender.com";


/* =========================
   ANONYMOUS USER ID
========================= */

function getAnonymousId() {
    let id = localStorage.getItem("randomconnect_id");

    if (!id) {
        if (
            typeof crypto !== "undefined" &&
            crypto.randomUUID
        ) {
            id = crypto.randomUUID();
        } else {
            id =
                "user-" +
                Date.now() +
                "-" +
                Math.random().toString(36).slice(2);
        }

        localStorage.setItem("randomconnect_id", id);
    }

    return id;
}


/* =========================
   DARK MODE
========================= */

function setupTheme() {
    const savedTheme =
        localStorage.getItem("randomconnect_theme");

    if (savedTheme === "dark") {
        document.body.classList.add("dark");
    }

    let themeButton =
        document.getElementById("theme-toggle");

    if (!themeButton) {
        themeButton =
            document.createElement("button");

        themeButton.id = "theme-toggle";
        themeButton.className = "theme-toggle";
        themeButton.type = "button";

        const nav = document.querySelector("nav");

        if (nav) {
            const list = nav.querySelector("ul");

            if (list) {
                const li =
                    document.createElement("li");

                li.appendChild(themeButton);
                list.appendChild(li);
            } else {
                nav.appendChild(themeButton);
            }
        }
    }

    if (!themeButton) {
        return;
    }

    function updateThemeButton() {
        const dark =
            document.body.classList.contains("dark");

        themeButton.innerHTML =
            dark
                ? "☀️ Light"
                : "🌙 Dark";
    }

    updateThemeButton();

    themeButton.addEventListener(
        "click",
        function () {
            document.body.classList.toggle("dark");

            const dark =
                document.body.classList.contains("dark");

            localStorage.setItem(
                "randomconnect_theme",
                dark ? "dark" : "light"
            );

            updateThemeButton();
        }
    );
}


/* =========================
   RANDOM CHAT ELEMENTS
========================= */

const matchingScreen =
    document.getElementById("matching-screen");

const conversation =
    document.getElementById("conversation");

const chatStatus =
    document.getElementById("chat-status");

const chatDescription =
    document.getElementById("chat-description");

const chatActionBtn =
    document.getElementById("chat-action-btn");

const messageForm =
    document.getElementById("message-form");

const messageInput =
    document.getElementById("message-input");

const messages =
    document.getElementById("messages");

const skipButton =
    document.getElementById("skip-btn");

const leaveChatButton =
    document.getElementById("leave-chat");


let randomSocket = null;
let randomConnected = false;

/*
 * IMPORTANT:
 * This is the ID generated by the RANDOM CHAT SERVER.
 * It is different from the localStorage ID used by groups.
 */
let randomServerUserId = null;


/* =========================
   RANDOM CHAT UI
========================= */

function showRandomWaiting(
    text = "Looking for someone to chat with..."
) {
    randomConnected = false;

    if (matchingScreen) {
        matchingScreen.style.display = "flex";
    }

    if (conversation) {
        conversation.style.display = "none";
    }

    if (chatStatus) {
        chatStatus.textContent = "Searching...";
    }

    if (chatDescription) {
        chatDescription.textContent = text;
    }

    if (messages) {
        messages.innerHTML = "";
    }
}


function showRandomConversation() {
    randomConnected = true;

    if (matchingScreen) {
        matchingScreen.style.display = "none";
    }

    if (conversation) {
        conversation.style.display = "flex";
    }

    if (chatStatus) {
        chatStatus.textContent = "Connected";
    }

    if (chatDescription) {
        chatDescription.textContent =
            "You are chatting anonymously.";
    }

    if (messageInput) {
        messageInput.focus();
    }
}


/* =========================
   RANDOM CHAT CONNECTION
========================= */

function connectRandomChat() {
    if (!matchingScreen || !conversation) {
        return;
    }

    randomServerUserId = null;

    showRandomWaiting();

    const protocol =
        window.location.protocol === "https:"
            ? "wss:"
            : "ws:";

    randomSocket =
        new WebSocket(
            `${WS_URL}/ws/random`
        );


    randomSocket.addEventListener(
        "open",
        function () {
            console.log(
                "Random chat connected"
            );
        }
    );


    randomSocket.addEventListener(
        "message",
        function (event) {

            let data;

            try {
                data = JSON.parse(event.data);
            } catch (error) {
                console.error(
                    "Invalid random chat data:",
                    error
                );
                return;
            }

            console.log(
                "RANDOM EVENT:",
                data
            );


            /* =====================
               WAITING
            ===================== */

            if (data.type === "waiting") {

                /*
                 * Backend sends our server-side
                 * anonymous ID here.
                 */
                if (data.user_id) {
                    randomServerUserId =
                        data.user_id;

                    console.log(
                        "My random server ID:",
                        randomServerUserId
                    );
                }

                showRandomWaiting(
                    data.message ||
                    "Looking for someone to chat with..."
                );
            }


            /* =====================
               MATCHED
            ===================== */

            else if (data.type === "matched") {

                /*
                 * Store our server-side ID again
                 * when a match is created.
                 */
                if (data.user_id) {
                    randomServerUserId =
                        data.user_id;

                    console.log(
                        "Matched - my server ID:",
                        randomServerUserId
                    );
                }

                showRandomConversation();
            }


            /* =====================
               MESSAGE
            ===================== */

            else if (data.type === "message") {

                if (!messages) {
                    return;
                }

                /*
                 * THIS FIXES THE BUBBLE PROBLEM.
                 *
                 * If sender_id equals our server ID,
                 * show the message on the RIGHT.
                 *
                 * Otherwise show it on the LEFT.
                 */
                const isMine =
                    data.sender_id ===
                    randomServerUserId;

                addRandomMessage(
                    data.content,
                    isMine
                );
            }


            /* =====================
               PARTNER SKIPPED
            ===================== */

            else if (
                data.type === "partner_skipped"
            ) {

                showRandomWaiting(
                    "The other person skipped. Finding someone new..."
                );
            }


            /* =====================
               PARTNER LEFT
            ===================== */

            else if (
                data.type === "partner_left"
            ) {

                randomConnected = false;

                if (chatStatus) {
                    chatStatus.textContent =
                        "Partner left";
                }

                if (chatDescription) {
                    chatDescription.textContent =
                        "The other person left the chat.";
                }

                if (matchingScreen) {
                    matchingScreen.style.display =
                        "flex";
                }

                if (conversation) {
                    conversation.style.display =
                        "none";
                }

                if (messages) {
                    messages.innerHTML = "";
                }
            }


            /* =====================
               SKIP BLOCKED
            ===================== */

            else if (
                data.type === "skip_blocked"
            ) {

                alert(
                    data.message ||
                    "You cannot skip right now."
                );
            }


            /* =====================
               ERROR
            ===================== */

            else if (
                data.type === "error"
            ) {

                console.error(
                    "Random chat error:",
                    data.message
                );
            }
        }
    );


    randomSocket.addEventListener(
        "close",
        function () {

            randomConnected = false;

            if (chatStatus) {
                chatStatus.textContent =
                    "Disconnected";
            }

            if (chatDescription) {
                chatDescription.textContent =
                    "Connection closed.";
            }
        }
    );


    randomSocket.addEventListener(
        "error",
        function (error) {

            console.error(
                "Random chat error:",
                error
            );
        }
    );
}


/* =========================
   RANDOM MESSAGE UI
========================= */

function addRandomMessage(
    content,
    isMine
) {
    if (!messages) {
        return;
    }

    const message =
        document.createElement("div");

    /*
     * Your message:
     * message sent
     *
     * Partner message:
     * message received
     */
    message.className =
        isMine
            ? "message sent"
            : "message received";


    const paragraph =
        document.createElement("p");

    paragraph.textContent =
        content;

    message.appendChild(
        paragraph
    );

    messages.appendChild(
        message
    );

    messages.scrollTop =
        messages.scrollHeight;
}


/* =========================
   RANDOM SEND MESSAGE
========================= */

if (messageForm) {

    messageForm.addEventListener(
        "submit",
        function (event) {

            event.preventDefault();

            if (
                !randomSocket ||
                randomSocket.readyState !==
                    WebSocket.OPEN
            ) {
                return;
            }

            if (!randomConnected) {
                return;
            }

            const content =
                messageInput
                    ? messageInput.value.trim()
                    : "";

            if (!content) {
                return;
            }

            randomSocket.send(
                JSON.stringify({
                    type: "message",
                    content: content
                })
            );

            messageInput.value = "";

            messageInput.focus();
        }
    );
}


/* =========================
   RANDOM SKIP
========================= */

if (skipButton) {

    skipButton.addEventListener(
        "click",
        function () {

            if (
                !randomSocket ||
                randomSocket.readyState !==
                    WebSocket.OPEN
            ) {
                return;
            }

            if (!randomConnected) {
                return;
            }

            randomSocket.send(
                JSON.stringify({
                    type: "skip"
                })
            );
        }
    );
}


/* =========================
   RANDOM LEAVE
========================= */

if (leaveChatButton) {

    leaveChatButton.addEventListener(
        "click",
        function () {

            if (
                randomSocket &&
                randomSocket.readyState ===
                    WebSocket.OPEN
            ) {

                randomSocket.send(
                    JSON.stringify({
                        type: "leave"
                    })
                );

                randomSocket.close();
            }

            window.location.href =
                "index.html";
        }
    );
}


/* =========================
   OLD ACTION BUTTON
========================= */

if (chatActionBtn) {

    chatActionBtn.addEventListener(
        "click",
        function () {

            if (
                randomSocket &&
                randomSocket.readyState ===
                    WebSocket.OPEN
            ) {

                if (randomConnected) {

                    randomSocket.send(
                        JSON.stringify({
                            type: "skip"
                        })
                    );

                } else {

                    randomSocket.close();

                    window.location.href =
                        "index.html";
                }

            } else {

                window.location.href =
                    "index.html";
            }
        }
    );
}


/* =========================
   START RANDOM CHAT
========================= */

if (
    matchingScreen &&
    conversation
) {
    connectRandomChat();
}


/* =========================
   GROUP PAGE
========================= */

const createGroupForm =
    document.getElementById(
        "create-group-form"
    );

const joinGroupForm =
    document.getElementById(
        "join-group-form"
    );

const groupNameInput =
    document.getElementById(
        "group-name"
    );

const groupCodeInput =
    document.getElementById(
        "group-code"
    );

const groupResult =
    document.getElementById(
        "group-result"
    );


/* =========================
   CREATE GROUP
========================= */

if (createGroupForm) {

    createGroupForm.addEventListener(
        "submit",
        async function (event) {

            event.preventDefault();

            const groupName =
                groupNameInput
                    ? groupNameInput.value.trim()
                    : "";

            if (!groupName) {
                return;
            }

            try {

                const response =
                    await fetch(
                        `${API_URL}/api/groups`,
                        {
                            method: "POST",

                            headers: {
                                "Content-Type":
                                    "application/json"
                            },

                            body:
                                JSON.stringify({
                                    name:
                                        groupName
                                })
                        }
                    );

                const data =
                    await response.json();

                if (!response.ok) {

                    if (groupResult) {

                        groupResult.style.display =
                            "block";

                        groupResult.innerHTML = `
                            <h3>Unable to Create Group</h3>
                            <p>
                                ${data.detail ||
                                "Something went wrong."}
                            </p>
                        `;
                    }

                    return;
                }

                if (groupResult) {

                    groupResult.style.display =
                        "block";

                    groupResult.innerHTML = `
                        <h3>✓ Group Created!</h3>

                        <p>
                            Your group
                            <strong>${data.name}</strong>
                            is ready.
                        </p>

                        <p>
                            Group code:
                        </p>

                        <h2>${data.code}</h2>

                        <p>
                            Opening group chat...
                        </p>
                    `;
                }

                if (groupNameInput) {
                    groupNameInput.value = "";
                }

                setTimeout(
                    function () {

                        window.location.href =
                            `group-chat.html?code=${
                                encodeURIComponent(
                                    data.code
                                )
                            }`;

                    },
                    800
                );

            } catch (error) {

                console.error(
                    "Group creation failed:",
                    error
                );

                if (groupResult) {

                    groupResult.style.display =
                        "block";

                    groupResult.innerHTML = `
                        <h3>Connection Error</h3>

                        <p>
                            Unable to connect to the server.
                        </p>
                    `;
                }
            }
        }
    );
}


/* =========================
   JOIN GROUP
========================= */

if (joinGroupForm) {

    joinGroupForm.addEventListener(
        "submit",
        async function (event) {

            event.preventDefault();

            const groupCode =
                groupCodeInput
                    ? groupCodeInput.value
                        .trim()
                        .toUpperCase()
                    : "";

            if (!groupCode) {
                return;
            }

            try {

                const response =
                    await fetch(
                        `${API_URL}/api/groups/join`,
                        {
                            method: "POST",

                            headers: {
                                "Content-Type":
                                    "application/json"
                            },

                            body:
                                JSON.stringify({
                                    code:
                                        groupCode
                                })
                        }
                    );

                const data =
                    await response.json();

                if (!response.ok) {

                    if (groupResult) {

                        groupResult.style.display =
                            "block";

                        groupResult.innerHTML = `
                            <h3>Unable to Join</h3>

                            <p>
                                ${data.detail ||
                                "Group not found."}
                            </p>
                        `;
                    }

                    return;
                }

                if (groupResult) {

                    groupResult.style.display =
                        "block";

                    groupResult.innerHTML = `
                        <h3>✓ Joined Successfully!</h3>

                        <p>
                            You joined
                            <strong>${data.name}</strong>
                        </p>

                        <p>
                            Opening group chat...
                        </p>
                    `;
                }

                if (groupCodeInput) {
                    groupCodeInput.value = "";
                }

                setTimeout(
                    function () {

                        window.location.href =
                            `group-chat.html?code=${
                                encodeURIComponent(
                                    data.code
                                )
                            }`;

                    },
                    800
                );

            } catch (error) {

                console.error(
                    "Group join failed:",
                    error
                );

                if (groupResult) {

                    groupResult.style.display =
                        "block";

                    groupResult.innerHTML = `
                        <h3>Connection Error</h3>

                        <p>
                            Unable to connect to the server.
                        </p>
                    `;
                }
            }
        }
    );
}


/* =========================
   GROUP CHAT ELEMENTS
========================= */

const groupTitle =
    document.getElementById(
        "group-title"
    );

const groupCodeElement =
    document.getElementById(
        "group-code"
    );

const groupMessages =
    document.getElementById(
        "group-messages"
    );

const emptyMessage =
    document.getElementById(
        "empty-message"
    );

const groupMessageForm =
    document.getElementById(
        "group-message-form"
    );

const groupMessageInput =
    document.getElementById(
        "group-message-input"
    );

const groupChatStatus =
    document.getElementById(
        "group-chat-status"
    );

const groupSendButton =
    document.getElementById(
        "send-button"
    );

const groupLeaveButton =
    document.getElementById(
        "group-leave"
    );


/* =========================
   GROUP CHAT
========================= */

if (
    groupTitle &&
    groupMessages &&
    groupMessageForm
) {

    const params =
        new URLSearchParams(
            window.location.search
        );

    const groupCode =
        (
            params.get("code") ||
            ""
        ).toUpperCase();

    const groupUserId =
        getAnonymousId();

    let groupSocket = null;


    /* =====================
       GROUP URLS
    ===================== */

    function getGroupUrl() {

        return `${API_URL}/api/groups/${
            encodeURIComponent(
                groupCode
            )
        }`;
    }


    function getMessagesUrl() {

        return `${getGroupUrl()}/messages`;
    }


    /* =====================
       GROUP STATUS
    ===================== */

    function setGroupStatus(
        text,
        connected = false
    ) {

        if (!groupChatStatus) {
            return;
        }

        groupChatStatus.textContent =
            text;

        groupChatStatus.classList.toggle(
            "connected",
            connected
        );

        groupChatStatus.classList.toggle(
            "disconnected",
            !connected
        );
    }


    /* =====================
       LOAD GROUP
    ===================== */

    async function loadGroup() {

        const response =
            await fetch(
                getGroupUrl()
            );

        if (!response.ok) {

            throw new Error(
                "Group not found"
            );
        }

        const group =
            await response.json();

        groupTitle.textContent =
            group.name;

        if (groupCodeElement) {

            groupCodeElement.textContent =
                group.code;
        }
    }


    /* =====================
       LOAD GROUP MESSAGES
    ===================== */

    async function loadGroupMessages() {

        const response =
            await fetch(
                getMessagesUrl()
            );

        if (!response.ok) {
            return;
        }

        const oldMessages =
            await response.json();

        if (
            oldMessages.length > 0 &&
            emptyMessage
        ) {

            emptyMessage.style.display =
                "none";
        }

        oldMessages.forEach(
            function (message) {

                addGroupMessage(
                    message
                );
            }
        );
    }


    /* =====================
       ADD GROUP MESSAGE
    ===================== */

    function addGroupMessage(
        message
    ) {

        if (!groupMessages) {
            return;
        }

        if (emptyMessage) {

            emptyMessage.style.display =
                "none";
        }

        const isMine =
            message.sender_id ===
            groupUserId;

        const wrapper =
            document.createElement(
                "div"
            );

        wrapper.className =
            isMine
                ? "chat-message own"
                : "chat-message";

        const bubble =
            document.createElement(
                "div"
            );

        bubble.className =
            "bubble";

        bubble.textContent =
            message.content;

        const meta =
            document.createElement(
                "small"
            );

        meta.className =
            "meta";

        meta.textContent =
            isMine
                ? "You"
                : "Anonymous";

        wrapper.appendChild(
            bubble
        );

        wrapper.appendChild(
            meta
        );

        groupMessages.appendChild(
            wrapper
        );

        groupMessages.scrollTop =
            groupMessages.scrollHeight;
    }


    /* =====================
       CONNECT GROUP
    ===================== */

    function connectToGroup() {

        const protocol =
            window.location.protocol === "https:"
                ? "wss:"
                : "ws:";

        groupSocket =
            new WebSocket(
                `${WS_URL}/ws/groups/${
                    encodeURIComponent(
                        groupCode
                    )
                }`
            );

        groupSocket.addEventListener(
            "open",
            function () {

                console.log(
                    "Group chat connected"
                );

                setGroupStatus(
                    "Connected",
                    true
                );

                if (groupSendButton) {

                    groupSendButton.disabled =
                        false;
                }

                if (groupMessageInput) {

                    groupMessageInput.focus();
                }
            }
        );


        groupSocket.addEventListener(
            "message",
            function (event) {

                let data;

                try {

                    data =
                        JSON.parse(
                            event.data
                        );

                } catch (error) {

                    console.error(
                        "Invalid group chat data:",
                        error
                    );

                    return;
                }

                console.log(
                    "GROUP EVENT:",
                    data
                );


                /* CONNECTED */

                if (
                    data.type ===
                    "connected"
                ) {

                    setGroupStatus(
                        "Connected",
                        true
                    );

                    if (data.group) {

                        groupTitle.textContent =
                            data.group.name;

                        if (groupCodeElement) {

                            groupCodeElement.textContent =
                                data.group.code;
                        }
                    }
                }


                /* MESSAGE */

                else if (
                    data.type ===
                    "message"
                ) {

                    addGroupMessage(
                        data
                    );
                }


                /* GROUP DELETED */

                else if (
                    data.type ===
                    "group_deleted"
                ) {

                    setGroupStatus(
                        "Group deleted",
                        false
                    );

                    alert(
                        data.reason ||
                        "This group has expired."
                    );

                    window.location.href =
                        "group.html";
                }


                /* ERROR */

                else if (
                    data.type ===
                    "error"
                ) {

                    console.error(
                        "Group chat error:",
                        data.message
                    );
                }
            }
        );


        groupSocket.addEventListener(
            "close",
            function () {

                console.log(
                    "Group chat disconnected"
                );

                setGroupStatus(
                    "Disconnected",
                    false
                );

                if (groupSendButton) {

                    groupSendButton.disabled =
                        true;
                }
            }
        );


        groupSocket.addEventListener(
            "error",
            function (error) {

                console.error(
                    "Group WebSocket error:",
                    error
                );

                setGroupStatus(
                    "Connection error",
                    false
                );

                if (groupSendButton) {

                    groupSendButton.disabled =
                        true;
                }
            }
        );
    }


    /* =====================
       SEND GROUP MESSAGE
    ===================== */

    groupMessageForm.addEventListener(
        "submit",
        function (event) {

            event.preventDefault();

            const content =
                groupMessageInput
                    ? groupMessageInput.value.trim()
                    : "";

            if (!content) {
                return;
            }

            if (
                !groupSocket ||
                groupSocket.readyState !==
                    WebSocket.OPEN
            ) {
                return;
            }

            groupSocket.send(
                JSON.stringify({
                    type: "message",
                    sender_id: groupUserId,
                    content: content
                })
            );

            groupMessageInput.value = "";

            groupMessageInput.focus();
        }
    );


    /* =====================
       LEAVE GROUP
    ===================== */

    if (groupLeaveButton) {

        groupLeaveButton.addEventListener(
            "click",
            function () {

                if (groupSocket) {
                    groupSocket.close();
                }

                window.location.href =
                    "group.html";
            }
        );
    }


    /* =====================
       START GROUP CHAT
    ===================== */

    async function startGroupChat() {

        if (!groupCode) {

            alert(
                "No group code provided."
            );

            window.location.href =
                "group.html";

            return;
        }

        try {

            await loadGroup();

            await loadGroupMessages();

            connectToGroup();

        } catch (error) {

            console.error(
                "Group loading failed:",
                error
            );

            alert(
                "Group not found."
            );

            window.location.href =
                "group.html";
        }
    }


    startGroupChat();
}


/* =========================
   BACKEND CONNECTION TEST
========================= */

async function checkBackend() {

    try {

        const response =
            await fetch(
                `${API_URL}/api/status`
            );

        const data =
            await response.json();

        console.log(
            "Backend connected:",
            data
        );

    } catch (error) {

        console.error(
            "Backend connection failed:",
            error
        );
    }
}


/* =========================
   START
========================= */

setupTheme();

checkBackend();